# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2025 Euro-Office

name: MYSQL database tests
on:
  push:
    branches:
      - '**'
    paths:
      - 'tests/integration/databaseTests/**'
      - 'DocService/sources/databaseConnectors/baseConnector.js'
      - 'DocService/sources/databaseConnectors/mysqlConnector.js'
      - '.forgejo/workflows/mysql-tests.yml'
jobs:
  mysql-tests:
    name: MYSQL
    runs-on: docker
    container: node:20-bookworm
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: world-office
          MYSQL_DATABASE: world-office
        ports:
          - 8080:3306
          - 8081:33060
        options: --name ci_mysql

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Caching dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ./npm-shrinkwrap.json
            ./Common/npm-shrinkwrap.json
            ./DocService/npm-shrinkwrap.json

      - name: Install modules
        run: |
          npm ci
          npm --prefix Common ci
          npm --prefix DocService ci

      - name: Creating service DB configuration
        run: |
          echo '{"services": {"CoAuthoring": {"sql": {"type": "mysql", "dbHost": "127.0.0.1", "dbPort": "8080", "dbUser": "root", "dbPass": "world-office"}}}}' >> Common/config/local.json

      - name: Wait for MySQL to be ready
        run: |
          until docker exec ci_mysql sh -c 'mysqladmin ping -uroot -pworld-office --silent'; do sleep 1; done

      - name: Creating schema
        run: |
          docker exec -i ci_mysql mysql -uroot -pworld-office -D world-office < schema/mysql/createdb.sql

      - name: Run Jest
        run: npm run "integration database tests"