# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2025 word-office

name: Postgre database tests
on:
  push:
    branches:
      - '**'
    paths:
      - 'tests/integration/databaseTests/**'
      - 'DocService/sources/databaseConnectors/baseConnector.js'
      - 'DocService/sources/databaseConnectors/postgreConnector.js'
jobs:
  postgres-tests:
    name: Postgres
    runs-on: docker
    container: node:20-bookworm
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: world-office
          POSTGRES_USER: world-office
          POSTGRES_DB: world-office
        ports:
          - 5432:5432
        options: --name postgres

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Caching dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ./npm-shrinkwrap.json
            ./Common/npm-shrinkwrap.json
            ./DocService/npm-shrinkwrap.json

      - name: Install modules
        run: |
          npm ci
          npm --prefix Common ci
          npm --prefix DocService ci

      - name: Creating service DB configuration
        run: |
          echo '{"services": {"CoAuthoring": {"sql": {"dbHost": "127.0.0.1", "pgPoolExtraOptions": {"options": "-c search_path=ci_test"}}}}}' >> Common/config/local.json

      - name: Wait for Postgres to be ready
        run: |
          until docker exec postgres pg_isready -U world-office; do sleep 1; done

      - name: Creating schema
        run: |
          docker exec postgres psql -d world-office -U world-office -c "CREATE SCHEMA IF NOT EXISTS ci_test;"
          docker cp ./schema/postgresql/createdb.sql postgres:/
          docker exec postgres bash -c 'PGOPTIONS="-c search_path=ci_test" psql -d world-office -U world-office -a -f /createdb.sql'

      - name: Run Jest
        run: npm run "integration database tests"