// WasmRenderer — canvas rendering bridge for wo-renderer-wasm (PDF)
//
// This module provides the integration surface that will eventually call
// into wo-renderer-wasm's render_page(). For now it draws a realistic
// PDF page preview (white page with simulated text, headers, and page
// numbers) directly on an HTML5 Canvas.
//
// TODO: Connect to wo-renderer-wasm render_page() when WASM is bundled

/** Dimensions of a PDF page in points (1 point = 1/72 inch). */
const PAGE_WIDTH_PT = 595
const PAGE_HEIGHT_PT = 842
const MARGIN_PT = 72
const CONTENT_TOP_PT = MARGIN_PT + 20
const LINE_HEIGHT_PT = 16
const CHAR_WIDTH_PT = 7.2

/** Canvas pixel density for crisp rendering. */
const DPR = typeof window !== "undefined" ? Math.min(window.devicePixelRatio || 1, 2) : 1

interface RendererState {
  canvas: HTMLCanvasElement | null
  ctx: CanvasRenderingContext2D | null
  totalPages: number
}

const state: RendererState = {
  canvas: null,
  ctx: null,
  totalPages: 5,
}

/** Seeded pseudo-random for deterministic line widths per page. */
function seededRandom(seed: number): () => number {
  let s = seed
  return () => {
    s = (s * 16807 + 0) % 2147483647
    return (s - 1) / 2147483646
  }
}

function drawPage(pageIndex: number): void {
  const { ctx } = state
  if (!ctx) return

  ctx.save()
  ctx.scale(DPR, DPR)
  ctx.clearRect(0, 0, PAGE_WIDTH_PT, PAGE_HEIGHT_PT)

  // Page shadow
  ctx.fillStyle = "rgba(0, 0, 0, 0.08)"
  ctx.fillRect(2, 2, PAGE_WIDTH_PT, PAGE_HEIGHT_PT)

  // Page background
  ctx.fillStyle = "#ffffff"
  ctx.fillRect(0, 0, PAGE_WIDTH_PT, PAGE_HEIGHT_PT)

  // Draw simulated PDF content
  const rng = seededRandom(pageIndex * 1000 + 99)
  const contentWidth = PAGE_WIDTH_PT - 2 * MARGIN_PT
  let y = CONTENT_TOP_PT

  // PDF-style header
  if (pageIndex === 0) {
    ctx.fillStyle = "#1a1a2e"
    ctx.font = "bold 20pt 'Georgia', 'Times New Roman', serif"
    ctx.fillText("World Office — PDF Document", MARGIN_PT, y)
    y += LINE_HEIGHT_PT * 2

    ctx.fillStyle = "#666666"
    ctx.font = "10pt 'Segoe UI', Arial, sans-serif"
    ctx.fillText("Generated by World Office PDF Viewer", MARGIN_PT, y)
    y += LINE_HEIGHT_PT * 1.5

    ctx.strokeStyle = "#cccccc"
    ctx.lineWidth = 0.8
    ctx.beginPath()
    ctx.moveTo(MARGIN_PT, y)
    ctx.lineTo(PAGE_WIDTH_PT - MARGIN_PT, y)
    ctx.stroke()
    y += LINE_HEIGHT_PT * 1.5
  } else {
    // Subsequent pages have a section header
    ctx.fillStyle = "#1a1a2e"
    ctx.font = "bold 14pt 'Georgia', 'Times New Roman', serif"
    ctx.fillText(`Section ${pageIndex + 1}`, MARGIN_PT, y)
    y += LINE_HEIGHT_PT * 1.8

    ctx.strokeStyle = "#dddddd"
    ctx.lineWidth = 0.5
    ctx.beginPath()
    ctx.moveTo(MARGIN_PT, y)
    ctx.lineTo(MARGIN_PT + 120, y)
    ctx.stroke()
    y += LINE_HEIGHT_PT * 1.2
  }

  // Paragraph text lines (serif font for PDF feel)
  ctx.fillStyle = "#333333"
  ctx.font = "11pt 'Georgia', 'Times New Roman', serif"

  const pageBottom = PAGE_HEIGHT_PT - MARGIN_PT - 30
  let paraGap = 0

  while (y < pageBottom) {
    paraGap++
    if (paraGap > 5 && rng() > 0.55) {
      y += LINE_HEIGHT_PT * 1.2
      paraGap = 0
      continue
    }

    const indent = paraGap === 1 ? 20 : 0
    const lineWidth = contentWidth * (0.7 + rng() * 0.28) - indent
    const lineLen = Math.floor(lineWidth / CHAR_WIDTH_PT)

    const chars = "abcdefghijklmnopqrstuvwxyz"
    let text = ""
    for (let i = 0; i < lineLen; i++) {
      text += chars[Math.floor(rng() * chars.length)]
      if (rng() < 0.15) text += " "
    }
    text = text.charAt(0).toUpperCase() + text.slice(1)

    ctx.fillText(text, MARGIN_PT + indent, y)
    y += LINE_HEIGHT_PT
  }

  // Page number at bottom center
  ctx.fillStyle = "#888888"
  ctx.font = "9pt 'Segoe UI', Arial, sans-serif"
  ctx.textAlign = "center"
  ctx.fillText(`${pageIndex + 1} / ${state.totalPages}`, PAGE_WIDTH_PT / 2, PAGE_HEIGHT_PT - MARGIN_PT / 2 + 10)
  ctx.textAlign = "start"

  // Page border
  ctx.strokeStyle = "#dddddd"
  ctx.lineWidth = 0.5
  ctx.strokeRect(0, 0, PAGE_WIDTH_PT, PAGE_HEIGHT_PT)

  ctx.restore()
}

/** Initialize the renderer with a canvas element. */
export function init(canvas: HTMLCanvasElement): void {
  state.canvas = canvas
  state.ctx = canvas.getContext("2d", { alpha: false })

  if (state.ctx) {
    canvas.width = PAGE_WIDTH_PT * DPR
    canvas.height = PAGE_HEIGHT_PT * DPR
    canvas.style.width = `${PAGE_WIDTH_PT}px`
    canvas.style.height = `${PAGE_HEIGHT_PT}px`
  }
}

/** Render a specific page with the given zoom level (1 = 100%). */
export function renderPage(pageIndex: number, zoom: number): void {
  if (!state.canvas || !state.ctx) return

  const clampedPage = Math.max(0, Math.min(pageIndex, state.totalPages - 1))
  const scale = zoom / 100

  state.canvas.style.width = `${PAGE_WIDTH_PT * scale}px`
  state.canvas.style.height = `${PAGE_HEIGHT_PT * scale}px`

  drawPage(clampedPage)
}

/** Set total page count. */
export function setTotalPages(count: number): void {
  state.totalPages = Math.max(1, count)
}

/** Get the total page count. */
export function getTotalPages(): number {
  return state.totalPages
}
