const express = require('express');
const router = express.Router();
const fs = require('fs').promises;
const path = require('path');
const crypto = require('crypto');
const dotenv = require('dotenv');

/**
 * Safely read .env file values without triggering config.js validation.
 * Returns an object with string values (empty string for missing keys).
 */
function readEnvValues() {
  dotenv.config();
  const keys = [
    'OCIS_DOMAIN', 'DOCUMENT_SERVER_DOMAIN', 'OCIS_JWT_SECRET',
    'DOCUMENT_SERVER_JWT_SECRET', 'OCIS_IMAGE', 'DOCUMENT_SERVER_IMAGE',
    'TRAEFIK_IMAGE', 'ENABLE_SSL', 'PORT'
  ];
  const values = {};
  for (const key of keys) {
    values[key] = process.env[key] || '';
  }
  return values;
}

/**
 * Check if a .env file exists.
 */
async function envExists() {
  try {
    await fs.access(path.resolve(__dirname, '..', '.env'));
    return true;
  } catch {
    return false;
  }
}

/**
 * Validate domain format.
 */
function isValidDomain(domain) {
  const re = /^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$/;
  return re.test(domain);
}

/**
 * Validate setup form data.
 */
function validateForm(data) {
  const errors = {};

  if (!data.OCIS_DOMAIN || !data.OCIS_DOMAIN.trim()) {
    errors.OCIS_DOMAIN = 'OCIS domain is required';
  } else if (!isValidDomain(data.OCIS_DOMAIN.trim())) {
    errors.OCIS_DOMAIN = 'Invalid domain format (e.g. ocis.example.com)';
  }

  if (!data.DOCUMENT_SERVER_DOMAIN || !data.DOCUMENT_SERVER_DOMAIN.trim()) {
    errors.DOCUMENT_SERVER_DOMAIN = 'Document Server domain is required';
  } else if (!isValidDomain(data.DOCUMENT_SERVER_DOMAIN.trim())) {
    errors.DOCUMENT_SERVER_DOMAIN = 'Invalid domain format (e.g. docs.example.com)';
  }

  // JWT secrets — required when not auto-generating
  const autoSecrets = data._autoSecrets === 'true';
  if (!autoSecrets) {
    if (!data.OCIS_JWT_SECRET || data.OCIS_JWT_SECRET.length < 32) {
      errors.OCIS_JWT_SECRET = 'Must be at least 32 characters (or use auto-generate)';
    }
    if (!data.DOCUMENT_SERVER_JWT_SECRET || data.DOCUMENT_SERVER_JWT_SECRET.length < 32) {
      errors.DOCUMENT_SERVER_JWT_SECRET = 'Must be at least 32 characters (or use auto-generate)';
    }
  }

  if (data.PORT && isNaN(parseInt(data.PORT))) {
    errors.PORT = 'Port must be a valid number';
  }

  return errors;
}

/**
 * Generate a random base64 secret (32 bytes → ~44 chars).
 */
function generateSecret() {
  return crypto.randomBytes(32).toString('base64');
}

/**
 * Build the .env file content from form data.
 */
function buildEnvContent(data) {
  const autoSecrets = data._autoSecrets === 'true';

  const env = {
    PORT: data.PORT || '3000',
    NODE_ENV: 'production',
    OCIS_DOMAIN: data.OCIS_DOMAIN.trim(),
    DOCUMENT_SERVER_DOMAIN: data.DOCUMENT_SERVER_DOMAIN.trim(),
    OCIS_JWT_SECRET: autoSecrets ? generateSecret() : (data.OCIS_JWT_SECRET || generateSecret()),
    DOCUMENT_SERVER_JWT_SECRET: autoSecrets ? generateSecret() : (data.DOCUMENT_SERVER_JWT_SECRET || generateSecret()),
    OCIS_IMAGE: (data.OCIS_IMAGE || 'owncloud/ocis:latest').trim(),
    DOCUMENT_SERVER_IMAGE: (data.DOCUMENT_SERVER_IMAGE || 'world-office/documentserver:latest').trim(),
    TRAEFIK_IMAGE: (data.TRAEFIK_IMAGE || 'traefik:v2.10').trim(),
    TRAEFIK_HTTP_PORT: '80',
    TRAEFIK_HTTPS_PORT: '443',
    OCIS_INTERNAL_PORT: '9200',
    DOCUMENT_SERVER_INTERNAL_PORT: '80',
    OCIS_DATA_DIR: './data/ocis',
    DOCUMENT_SERVER_DATA_DIR: './data/documentserver',
    TRAEFIK_DATA_DIR: './data/traefik',
    ENABLE_SSL: data.ENABLE_SSL === 'true' ? 'true' : 'false',
    ENABLE_METRICS: 'true',
    ENABLE_LOGS: 'true'
  };

  let content = '# worldoffice-opencloud Configuration\n';
  content += '# Generated by setup wizard\n\n';
  for (const [key, value] of Object.entries(env)) {
    content += `${key}=${value}\n`;
  }
  return content;
}

// ── GET /setup ────────────────────────────────────────────────────────

router.get('/', async (req, res) => {
  try {
    const configured = await envExists();
    const currentValues = configured ? readEnvValues() : {
      OCIS_DOMAIN: '',
      DOCUMENT_SERVER_DOMAIN: '',
      OCIS_JWT_SECRET: '',
      DOCUMENT_SERVER_JWT_SECRET: '',
      OCIS_IMAGE: 'owncloud/ocis:latest',
      DOCUMENT_SERVER_IMAGE: 'world-office/documentserver:latest',
      TRAEFIK_IMAGE: 'traefik:v2.10',
      ENABLE_SSL: 'true',
      PORT: '3000'
    };

    const success = req.query.success === 'true';

    res.render('setup', {
      title: 'Setup — World Office Cloud',
      configured,
      config: currentValues,
      errors: {},
      success
    });
  } catch (error) {
    res.status(500).render('error', { title: 'Error', message: error.message });
  }
});

// ── POST /setup ───────────────────────────────────────────────────────

router.post('/', async (req, res) => {
  try {
    const errors = validateForm(req.body);

    if (Object.keys(errors).length > 0) {
      return res.render('setup', {
        title: 'Setup — World Office Cloud',
        configured: false,
        config: req.body,
        errors,
        success: false
      });
    }

    // Build and write .env
    const envContent = buildEnvContent(req.body);
    await fs.writeFile(path.resolve(__dirname, '..', '.env'), envContent, 'utf-8');

    // Generate docker-compose.yml using the compose module
    try {
      const { writeDockerCompose } = require('../lib/compose.js');
      await writeDockerCompose(path.resolve(__dirname, '..', 'docker-compose.yml'));
    } catch {
      // compose.js depends on config.js which needs the fresh .env.
      // Reload dotenv and retry once.
      dotenv.config({ override: true });
      try {
        const { writeDockerCompose } = require('../lib/compose.js');
        await writeDockerCompose(path.resolve(__dirname, '..', 'docker-compose.yml'));
      } catch (composeErr) {
        console.error('Could not generate docker-compose.yml:', composeErr.message);
      }
    }

    // Generate OCIS config files
    try {
      const { writeOcisConfig } = require('../lib/ocis-config.js');
      await writeOcisConfig(path.resolve(__dirname, '..', 'data', 'ocis', 'config'));
    } catch {
      dotenv.config({ override: true });
      try {
        const { writeOcisConfig } = require('../lib/ocis-config.js');
        await writeOcisConfig(path.resolve(__dirname, '..', 'data', 'ocis', 'config'));
      } catch (ocisErr) {
        console.error('Could not generate OCIS config:', ocisErr.message);
      }
    }

    res.redirect('/setup?success=true');
  } catch (error) {
    res.status(500).render('error', { title: 'Error', message: error.message });
  }
});

module.exports = router;
